# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Wolujewicz Lab"
title_separator: "-"
subtitle: "Computational Biomedicine and Integrative Genomics"
description: "Advancing discovery in neurogenomic disorders and vector-borne pathogens with integrative systems biology, AI-driven analytics, and multi-omic technologies."
name: "Paul Wolujewicz, PhD, MPH"
description: "Computational Biology and Genomics Laboratory at Quinnipiac University."
url: "https://wolujewiczlab.github.io"
baseurl: ""
repository: "wolujewiczlab/wolujewiczlab.github.io"
teaser: # path of fallback teaser image
logo: # path of logo image to display in the masthead
masthead_title: # overrides the website title displayed in the masthead
logo: "/assets/images/logo.png"

# Site Author
author:
  name: "Paul Wolujewicz, PhD, MPH"
  avatar: "/assets/images/bio-photo.jpg"
  bio: 'Assistant Professor of Biomedical Sciences at <a href="https://www.qu.edu" class="university-qu">Quinnipiac University</a>.<br>Adjunct Assistant Professor of Neuroscience at <a href="https://weill.cornell.edu" class="university-wcm">Weill Cornell Medicine</a>.'
  location: "Hamden, Connecticut, USA"
  avatar_link: "https://www.qu.edu/faculty-and-staff/paul-wolujewicz/"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/paul-wolujewicz-82b73314/"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0003-2982-9448"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:paul.wolujewicz@quinnipiac.edu"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
